// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCukQIUJ3VK1WEn7OH-RrETYAfcjl1Gb3M',
    appId: '1:193885194531:android:397df9e51c7b70174be496',
    messagingSenderId: '193885194531',
    projectId: 'project-19b8b',
    storageBucket: 'project-19b8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJrywqhR03ObwO2bAFKkrS_tyTZzqL8aQ',
    appId: '1:193885194531:ios:4f5db6368c8d9fc84be496',
    messagingSenderId: '193885194531',
    projectId: 'project-19b8b',
    storageBucket: 'project-19b8b.firebasestorage.app',
    androidClientId: '193885194531-tdrh54sj9599gp7p778lq2hg0g9vo74n.apps.googleusercontent.com',
    iosClientId: '193885194531-87tom23mc1rtvbod2589oi2maj79rl90.apps.googleusercontent.com',
    iosBundleId: 'com.example.authTest55',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6vwsfpcbgEusYMRp20rAK64glp1bOCW0',
    appId: '1:193885194531:web:9d58ade51d3b38e64be496',
    messagingSenderId: '193885194531',
    projectId: 'project-19b8b',
    authDomain: 'project-19b8b.firebaseapp.com',
    storageBucket: 'project-19b8b.firebasestorage.app',
  );

}